### ISSUE TITLE
Typo in the BitSharesBlockchain.pdf

### ISSUE THREAD

**Issue by sjaramillo10** [bitshares-foundation/bitshares.foundation#21]
The word 'it' is repeated twice in section 4 (BTS - The Utility Token), almost at the end of the paragraph.
"...aspects in a way it it can adapt..."

**Comment by xeroc** [comment]
Fixed here: https://github.com/bitshares-foundation/whitepapers/commit/647697224e477ab1080e2aed9c5ca723f6f466b6

thanks
